[versions]
agp = "8.7.3"
kotlin = "2.1.0"
compileSdk = "34"
minSdk = "24"
targetSdk = "34"
appcompat = "1.6.1"
fragmentKtx = "1.3.6"
material = "1.4.0"
multidex = "2.0.1"
lifecycleRuntime = "2.5.1"
lifecycleViewModel = "2.5.1"
lifecycleLivedata = "2.5.1"
room = "2.6.1"
workRuntime = "2.7.1"
eventbus = "3.2.0"
glide = "4.11.0"
rxjava2 = "2.2.20"
rxandroid = "2.1.1"
rxpermissions = "0.10.2"
rxlifecycle = "2.2.2"
arouter = "1.5.2"
utilcode = "1.31.0"
xxpermissions = "20.0"
xlog = "1.11.0"
photoView = "2.3.0"
androidPdfViewer = "2.8.1"
lottie = "6.0.0"
brvah = "3.0.10"
smartRefresh = "2.0.3"
loggingInterceptor = "4.9.0"
colorpickerview = "2.2.4"
mnImageBrowser = "V1.3.7"
compassSense = "6.2.0"
compassCore = "6.2.0"
nifty = "1.4.6"
javacv = "1.5.8"
javacpp = "1.5.8"
ffmpeg = "5.0-1.5.7"
gsyVideoPlayer = "v8.5.0-release-jitpack"
agconnect = "1.9.1.301"
jsbridge = "1.0.4"
fastjson = "1.2.78"
ucrop = "2.2.8"
immersionbar = "3.0.0"
xpopup = "2.10.0"
wechatSdk = "6.8.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntime" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModel" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedata" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntime" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxpermissions = { module = "com.github.tbruyelle:rxpermissions", version.ref = "rxpermissions" }
rxlifecycle = { module = "com.trello.rxlifecycle2:rxlifecycle", version.ref = "rxlifecycle" }
rxlifecycle-android = { module = "com.trello.rxlifecycle2:rxlifecycle-android", version.ref = "rxlifecycle" }
rxlifecycle-components = { module = "com.trello.rxlifecycle2:rxlifecycle-components", version.ref = "rxlifecycle" }
rxlifecycle-ktx = { module = "com.trello.rxlifecycle2:rxlifecycle-kotlin", version.ref = "rxlifecycle" }
rxlifecycle-android-lifecycle-ktx = { module = "com.trello.rxlifecycle2:rxlifecycle-android-lifecycle-kotlin", version.ref = "rxlifecycle" }
arouter-api = { module = "com.alibaba:arouter-api", version.ref = "arouter" }
arouter-compiler = { module = "com.alibaba:arouter-compiler", version.ref = "arouter" }
utilcode = { module = "com.blankj:utilcodex", version.ref = "utilcode" }
xxpermissions = { module = "com.github.getActivity:XXPermissions", version.ref = "xxpermissions" }
xlog = { module = "com.elvishew:xlog", version.ref = "xlog" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoView" }
android-pdf-viewer = { module = "com.github.barteksc:android-pdf-viewer", version.ref = "androidPdfViewer" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
brvah = { module = "com.github.cymchad:BaseRecyclerViewAdapterHelper", version.ref = "brvah" }
smartrefresh-kernel = { module = "com.scwang.smart:refresh-layout-kernel", version.ref = "smartRefresh" }
smartrefresh-header-classics = { module = "com.scwang.smart:refresh-header-classics", version.ref = "smartRefresh" }
smartrefresh-header-material = { module = "com.scwang.smart:refresh-header-material", version.ref = "smartRefresh" }
colorpickerview = { module = "com.github.skydoves:colorpickerview", version.ref = "colorpickerview" }
mnimagebrowser = { module = "com.github.maning0303:MNImageBrowser", version.ref = "mnImageBrowser" }
compass-sense = { module = "com.github.kylecorry31.andromeda:sense", version.ref = "compassSense" }
compass-core = { module = "com.github.kylecorry31.andromeda:core", version.ref = "compassCore" }
nifty-slider = { module = "io.github.litao0621:nifty-slider", version.ref = "nifty" }
nifty-slider-effect = { module = "io.github.litao0621:nifty-slider-effect", version.ref = "nifty" }
javacv = { module = "org.bytedeco:javacv", version.ref = "javacv" }
javacpp = { module = "org.bytedeco:javacpp", version.ref = "javacpp" }
ffmpeg-android-arm64 = { module = "org.bytedeco:ffmpeg", version.ref = "ffmpeg" }
ffmpeg-android-arm = { module = "org.bytedeco:ffmpeg", version.ref = "ffmpeg" }
ffmpeg-android-x86-64 = { module = "org.bytedeco:ffmpeg", version.ref = "ffmpeg" }
ffmpeg-android-x86 = { module = "org.bytedeco:ffmpeg", version.ref = "ffmpeg" }
gsyvideoplayer-java = { module = "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java", version.ref = "gsyVideoPlayer" }
gsyvideoplayer-exo2 = { module = "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so", version.ref = "gsyVideoPlayer" }
gsyvideoplayer-armv7a = { module = "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a", version.ref = "gsyVideoPlayer" }
gsyvideoplayer-arm64 = { module = "com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-arm64", version.ref = "gsyVideoPlayer" }
jsbridge = { module = "com.github.wendux:DSBridge-Android", version.ref = "jsbridge" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "fastjson" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }
immersionbar = { module = "com.gyf.immersionbar:immersionbar", version.ref = "immersionbar" }
immersionbar-ktx = { module = "com.gyf.immersionbar:immersionbar-ktx", version.ref = "immersionbar" }
xpopup = { module = "com.github.li-xiaojun:XPopup", version.ref = "xpopup" }
wechat-sdk = { module = "com.tencent.mm.opensdk:wechat-sdk-android-without-mta", version.ref = "wechatSdk" }
