[versions]
androidGradlePlugin = "8.7.3"
kotlin = "2.1.0"
#googleServices = "4.4.2" # Firebase removed
#firebaseCrashlyticsGradle = "3.0.2" # Firebase removed
huaweiAgconnect = "1.9.1.301"
arouterCompiler = "1.5.2"
jsbridge = "1.0.4"
fastjson = "2.0.53"
ucrop = "2.2.8"
appUpdate = "2.1.0"
immersionbar = "3.0.0"
xpopup = "2.10.0"
smartrefresh = "1.1.3"
wechatSdk = "6.8.0"
umengApm = "1.9.0"
mobilisten = "7.0.0"
#firebaseBom = "33.7.0" # Firebase removed
#firebaseMessaging = "24.1.0" # Firebase removed
umengCommon = "9.4.4+000"
umengCommonChina = "9.6.7"
umengAsms = "1.8.0"


[libraries]
arouter-compiler = { module = "com.alibaba:arouter-compiler", version.ref = "arouterCompiler" }
jsbridge = { module = "com.github.lzyzsd:jsbridge", version.ref = "jsbridge" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "fastjson" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
immersionbar = { module = "com.gyf.immersionbar:immersionbar", version.ref = "immersionbar" }
xpopup = { module = "com.github.li-xiaojun:XPopup", version.ref = "xpopup" }
smartrefresh-layout = { module = "com.scwang.smartrefresh:SmartRefreshLayout", version.ref = "smartrefresh" }
smartrefresh-header = { module = "com.scwang.smartrefresh:SmartRefreshHeader", version.ref = "smartrefresh" }
wechat-sdk = { module = "com.tencent.mm.opensdk:wechat-sdk-android", version.ref = "wechatSdk" }
umeng-apm = { module = "com.umeng.umsdk:apm", version.ref = "umengApm" }
mobilisten = { module = "com.zoho.salesiq:mobilisten", version.ref = "mobilisten" }
#firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" } # Firebase removed
#firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" } # Firebase removed
#firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" } # Firebase removed
#firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" } # Firebase removed
#firebase-iid = { module = "com.google.firebase:firebase-iid" } # Firebase removed
umeng-common-china = { module = "com.umeng.umsdk:common", version.ref = "umengCommonChina" }
umeng-asms = { module = "com.umeng.umsdk:asms", version.ref = "umengAsms" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" } # Firebase removed
#firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" } # Firebase removed
huawei-agconnect = { id = "com.huawei.agconnect", version.ref = "huaweiAgconnect" }
