have_fun: false
enabled_features:
  auto_review: true
  post_review_summary: true
  inline_suggestions: true
  review_pull_request: true
  severity_level: true

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: false
    code_review: true
    include_drafts: true

ignore_patterns:
  # Allow Markdown so Gemini can read AGENTS.md instructions.
  - "**/*.tex"
  - "**/*.latex"
  - "docs/**"
