have_fun: false
enabled_features:
  auto_review: true
  post_review_summary: true
  inline_suggestions: true
  review_pull_request: true
  severity_level: true

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: true
